import { Explanation, Features, Origin } from "../lib/types";
import { pct, signed } from "../lib/format";
import Panel from "./ui/Panel";

/** How the answer was produced. Never let a template fallback read as a live
 *  model response — during rehearsal this badge is the first thing to check. */
const SOURCE_COPY: Record<string, { label: string; tone: string; note: string }> = {
  granite: {
    label: "Granite",
    tone: "border-good/40 text-good",
    note: "Generated by watsonx Granite, with every quoted number validated against the divergence data.",
  },
  cached: {
    label: "Cached",
    tone: "border-predicted/40 text-predicted",
    note: "Replayed from an earlier Granite answer for an identical signature.",
  },
  template: {
    label: "Template",
    tone: "border-caution/40 text-caution",
    note: "Deterministic fallback from the signature table — no model was called.",
  },
  rule: {
    label: "Rule",
    tone: "border-muted/40 text-dim",
    note: "Decided by rule before any model call: the window contains no divergence.",
  },
};

export default function AIExplanation({
  explanation,
  origin,
  loading,
  error,
  emptyHint,
}: {
  explanation: Explanation | null;
  origin: Origin;
  loading: boolean;
  error?: string | null;
  emptyHint: string;
}) {
  const source = explanation
    ? SOURCE_COPY[explanation.source] ?? {
        label: explanation.source,
        tone: "border-edge text-muted",
        note: "Unrecognised source tag — check the /explain contract.",
      }
    : null;

  return (
    <Panel
      title="Diagnosis"
      aside={
        source && (
          <span
            title={source.note}
            className={`rounded border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.14em] ${source.tone}`}
          >
            {source.label}
          </span>
        )
      }
    >
      {loading && (
        <div className="space-y-2" aria-live="polite">
          <p className="text-sm text-muted">Reading the divergence…</p>
          <div className="h-3 w-4/5 animate-pulse rounded bg-raised" />
          <div className="h-3 w-full animate-pulse rounded bg-raised" />
          <div className="h-3 w-2/3 animate-pulse rounded bg-raised" />
        </div>
      )}

      {error && !loading && (
        <p className="rounded border-l-2 border-critical bg-hull px-3 py-2 text-sm text-critical">
          {error}
        </p>
      )}

      {!loading && !error && !explanation && (
        <p className="text-sm leading-relaxed text-muted">{emptyHint}</p>
      )}

      {!loading && explanation && (
        <div className="space-y-4">
          {origin === "fixture" && (
            <p className="rounded border-l-2 border-caution bg-hull px-3 py-2 text-xs leading-relaxed text-caution">
              Backend unreachable — this is the committed sample explanation from{" "}
              <code>backend/fixtures/explain.json</code>, not a diagnosis of the
              selected event.
            </p>
          )}

          <p className="text-base leading-snug text-ink">{explanation.headline}</p>
          <p className="text-sm leading-relaxed text-dim">{explanation.reasoning}</p>

          <dl className="space-y-2 border-t border-edge pt-3 text-sm">
            <Row label="Likely cause">
              {explanation.likely_cause ?? "indeterminate"}
            </Row>
            <Row label="Signature">
              <span className="tabular">{explanation.signature_id ?? "—"}</span>
            </Row>
            <Row label="Confidence">
              <span className="flex items-center gap-2">
                <span className="tabular w-9">{pct(explanation.confidence)}</span>
                <span
                  className="h-1.5 w-20 overflow-hidden rounded-full bg-edge"
                  role="img"
                  aria-label={`Confidence ${pct(explanation.confidence)}`}
                >
                  <span
                    className="block h-full rounded-full bg-predicted"
                    style={{ width: `${explanation.confidence * 100}%` }}
                  />
                </span>
              </span>
            </Row>
          </dl>

          {explanation.is_model_error && (
            <p className="rounded border-l-2 border-predicted bg-hull px-3 py-2 text-sm leading-relaxed text-dim">
              <span className="font-semibold text-ink">Modelling gap, not a fault.</span>{" "}
              The twin is wrong here, not the spacecraft. No command action.
            </p>
          )}

          <div className="border-t border-edge pt-3">
            <p className="mb-1 text-[11px] uppercase tracking-[0.14em] text-muted">
              Recommended action
            </p>
            <p className="text-sm leading-relaxed text-ink">
              {explanation.recommended_action}
            </p>
          </div>

          {explanation.features && <Evidence features={explanation.features} />}
        </div>
      )}
    </Panel>
  );
}

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex items-baseline justify-between gap-4">
      <dt className="shrink-0 text-muted">{label}</dt>
      <dd className="text-right text-ink">{children}</dd>
    </div>
  );
}

/** The exact numbers the model was allowed to see and quote. Showing them is what
 *  makes the answer auditable — an operator can check the prose against the
 *  evidence without leaving the panel. */
function Evidence({ features: f }: { features: Features }) {
  const rows: [string, string][] = [
    ["Shape", f.shape.replace(/_/g, " ")],
    ["Window", `${f.duration_min} min · ${f.sample_count} samples`],
    ["Peak residual", `${signed(f.peak_residual_c)} °C`],
    ["Mean residual", `${signed(f.mean_residual_c)} °C`],
    ["Slope", `${signed(f.residual_slope_c_per_hr, 3)} °C/hr`],
    ["Peak z", signed(f.peak_zscore, 2)],
    ["Sunlit mean", `${signed(f.sunlit_mean_residual_c)} °C`],
    ["Eclipse mean", `${signed(f.eclipse_mean_residual_c)} °C`],
  ];

  return (
    <details className="group border-t border-edge pt-3">
      <summary className="focusable cursor-pointer list-none text-[11px] uppercase tracking-[0.14em] text-muted hover:text-dim">
        Evidence
        <span className="ml-1 inline-block transition-transform group-open:rotate-90">
          ›
        </span>
      </summary>

      <p className="mt-2 text-xs leading-relaxed text-muted">
        {f.phase_correlation}.
      </p>

      <dl className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1 text-xs">
        {rows.map(([k, v]) => (
          <div key={k} className="flex justify-between gap-2 border-b border-edge/60 py-1">
            <dt className="text-muted">{k}</dt>
            <dd className="tabular text-dim">{v}</dd>
          </div>
        ))}
      </dl>

      {f.candidate_ids.length > 0 && (
        <p className="mt-2 text-xs text-muted">
          Candidates offered:{" "}
          <span className="tabular text-dim">{f.candidate_ids.join(", ")}</span>
        </p>
      )}
    </details>
  );
}
